### ISSUE TITLE
Release new version of gem for global_phone_dbgen 

### ISSUE THREAD

**Issue by daemonsy** [sstephenson/global_phone#14]
Hi guys, this commit changes the remote URL. 

Commit 7030736e9a9ebf971f46a4e8c75d4837e854102b

I just installed the gem, bumped into the 404 and took a while to fix the issue. 

Wanted to do a PR to help future users but realised it's already done. 

Would be nice if you realise a bump for rubygems, so new users don't bump into this problem.

**Comment by andyatkinson** [comment]
:+1:

**Comment by eileencodes** [comment]
The remote URL has been fixed in master. Thanks! :+1:

**Comment by locochris** [comment]
@eileencodes - perhaps you should leave this issue open until a new gem version has actually been released to:
  https://rubygems.org/gems/global_phone_dbgen

(We reference this gem in our own private gem so, as gemspecs only allow other gems to be sourced from rubygems, it remains an issue.)
