### ISSUE TITLE
Parsing Phone Numbers from Argentina

### ISSUE THREAD

**Issue by daemonsy** [sstephenson/global_phone#15]
Firstly, thank you for great library, we use it actively at work to parse phone numbers.

There seems to be an issue with parsing phone numbers from Argentina. 

Given a number, `+54 11 4799 9350`, it should be formatted as `+54 11 4799-9350`.

`GlobalPhone.parse("+54 11 4799 9350") # +54 9 11 4799-9350`

The extra 9 breaks the number because it is only supposed to be prefixed in front of mobile numbers.  (Wikipedia)[http://en.wikipedia.org/wiki/Telephone_numbers_in_Argentina]
 
I generated the the JSON file just today, supposed it's not because of libphonenumber and also, [Google's Javascript Demo](http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html) returns the right number. 

Would love to help if we can confirm this is some form of bug some pointers of where it might have gone wrong. It seems like the 9 is added in the method  `apply_national_prefix_format`

**Comment by futuretap** [comment]
@wallymathieu tried your proposed change (see https://github.com/futuretap/global_phone/commit/4cbdf32beeaa5650e0f92a6f5e7c7fe4f58e01e1) but the problem still persists. Did you do any other changes in the C# port?

**Comment by wallymathieu** [comment]
Yes, I've done merges of some the pull requests (ported to c#).

**Comment by wallymathieu** [comment]
BTW, you could do something like this : https://github.com/GlobalPhone/format_phonenumbers_server

**Comment by eileencodes** [comment]
I think this is fixed with the latest version. The phone number @daemonsy provided doesn't throw an error. If this does still throw an error can you please let me know and paste the error here? I'll reopen if this is still an issue.

**Comment by daemonsy** [comment]
Thank you! :)
