### ISSUE TITLE
Output Mismatch

### ISSUE THREAD

**Issue by hrishabhz** [sstephenson/global_phone#19]
http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html
Input: 911234567890, Default-Country: IN
Output: +91 1234 567 890

ph = GlobalPhone.parse('911234567890','IN')
ph.international_string = +91917893461643

No check, if country code added in case of without + sign.

**Comment by eileencodes** [comment]
I'm not sure I understand the issue. Can you clarify what you're seeing? I've merged #35 to master, does that address the issue you're talking about? Let me know if it doesn't and I'll reopen the issue. Thanks!
