### ISSUE TITLE
xml url invalid

### ISSUE THREAD

**Issue by bayusuwarninghadi** [sstephenson/global_phone#20]
by default global_phone_dbgen

Omit the filename argument to download and use the latest version of
Google's database from:      http://libphonenumber.googlecode.com/svn/trunk/resources/PhoneNumberMetaData.xml

should be:
http://libphonenumber.googlecode.com/svn/trunk/resources/PhoneNumberMetadata.xml

**Comment by eileencodes** [comment]
This is fixed on the latest master, thanks! :+1:
