### ISSUE TITLE
PhoneNumberMetadata.xml url

### ISSUE THREAD

**Issue by tomlobato** [sstephenson/global_phone#24]
Had to change 'd' to lower case in bin/global_phone_dbgen line 5

**Comment by beauby** [comment]
+1

**Comment by eileencodes** [comment]
This has been fixed but a new release hasn't been cut yet. Please use master for now if you want to get the new url. Thanks!

**Comment by beauby** [comment]
Wouldn't it make sense to issue a minor release?

**Comment by eileencodes** [comment]
@beauby I'll comment here when we release, but for now master is the most correct.
