### ISSUE TITLE
Segfault trying to execute global_phone_dbgen > db/global_phone.json

### ISSUE THREAD

**Issue by hraynaud** [sstephenson/global_phone#31]
global_phone_dbgen > db/global_phone.json
/Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/common.rb:67: [BUG] Segmentation fault at 0x00000000000018
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.

-- Control frame information -----------------------------------------------
c:0019 p:---- s:0089 e:000088 CFUNC  :initialize
c:0018 p:---- s:0087 e:000086 CFUNC  :new
c:0017 p:0075 s:0084 e:000081 METHOD /Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/common.rb:67
c:0016 p:0070 s:0073 e:000071 CLASS  /Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/ext.rb:17
c:0015 p:0011 s:0070 e:000069 CLASS  /Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/ext.rb:12
c:0014 p:0056 s:0068 e:000067 TOP    /Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/ext.rb:9 [FINISH]
c:0013 p:---- s:0066 e:000065 CFUNC  :require
c:0012 p:0113 s:0062 e:000061 METHOD /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54
c:0011 p:0019 s:0052 e:000051 CLASS  /Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json.rb:58
c:0010 p:0017 s:0050 e:000049 TOP    /Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json.rb:54 [FINISH]
c:0009 p:---- s:0048 e:000047 CFUNC  :require
c:0008 p:0113 s:0044 e:000043 METHOD /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54
c:0007 p:0007 s:0034 e:000033 TOP    /Users/herbyraynaud/.gem/gems/global_phone_dbgen-1.0.0/lib/global_phone/database_generator.rb:1 [FINISH]
c:0006 p:---- s:0032 e:000031 CFUNC  :require
c:0005 p:0113 s:0028 e:000027 METHOD /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54
c:0004 p:0007 s:0018 e:000017 TOP    /Users/herbyraynaud/.gem/gems/global_phone_dbgen-1.0.0/bin/global_phone_dbgen:2 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :load
c:0002 p:0135 s:0006 E:002700 EVAL   /Users/herbyraynaud/.gem/bin/global_phone_dbgen:23 [FINISH]
c:0001 p:0000 s:0002 E:002470 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/herbyraynaud/.gem/bin/global_phone_dbgen:23:in `<main>'
/Users/herbyraynaud/.gem/bin/global_phone_dbgen:23:in `load'
/Users/herbyraynaud/.gem/gems/global_phone_dbgen-1.0.0/bin/global_phone_dbgen:2:in `<top (required)>'
/Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/herbyraynaud/.gem/gems/global_phone_dbgen-1.0.0/lib/global_phone/database_generator.rb:1:in `<top (required)>'
/Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json.rb:54:in `<top (required)>'
/Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json.rb:58:in `<module:JSON>'
/Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/ext.rb:9:in `<top (required)>'
/Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/ext.rb:12:in `<module:JSON>'
/Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/ext.rb:17:in `<module:Ext>'
/Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/common.rb:67:in `generator='
/Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/common.rb:67:in `new'
/Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/common.rb:67:in `initialize'

-- Machine register context ------------------------------------------------
 rax: 0x0000000000000008 rbx: 0x0000000000000008 rcx: 0x0000000000000008
 rdx: 0x00007f9672c2d330 rdi: 0x0000000000000008 rsi: 0x0000000000a8110e
 rbp: 0x00007fff5e3db830 rsp: 0x00007fff5e3db810  r8: 0x0000000000000001
  r9: 0x0000000000000400 r10: 0x0000000000007000 r11: 0x0000000101890b90
 r12: 0x0000000000000008 r13: 0x00007f967408c890 r14: 0x0000000000a8110e
 r15: 0x00007f9672e4e8f0 rip: 0x0000000101890ba1 rfl: 0x0000000000010202

-- C level backtrace information -------------------------------------------
0   ruby                                0x00000001019bcdfb rb_vm_bugreport + 155
1   ruby                                0x00000001018613e0 rb_bug_context + 480
2   ruby                                0x0000000101939743 sigsegv + 83
3   libsystem_platform.dylib            0x00007fff925b5f1a _sigtramp + 26
4   ruby                                0x0000000101890ba1 rb_hash_aref + 17
5   ???                                 0x0000000000a8110e 0x0 + 11014414

-- Other runtime information -----------------------------------------------

* Loaded script: /Users/herbyraynaud/.gem/bin/global_phone_dbgen

* Loaded features:

    0 enumerator.so
    1 rational.so
    2 complex.so
    3 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/enc/encdb.bundle
    4 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/enc/trans/transdb.bundle
    5 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/unicode_normalize.rb
    6 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/rbconfig.rb
    7 thread.rb
    8 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/thread.bundle
    9 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/compatibility.rb
   10 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/defaults.rb
   11 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/deprecate.rb
   12 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/errors.rb
   13 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/version.rb
   14 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/requirement.rb
   15 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/platform.rb
   16 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/basic_specification.rb
   17 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/stub_specification.rb
   18 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/util/stringio.rb
   19 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/specification.rb
   20 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/exceptions.rb
   21 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb
   22 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb
   23 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb
   24 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems.rb
   25 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/dependency.rb
   26 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rubygems/path_support.rb
   27 /Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/version.rb
   28 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/ostruct.rb
   29 /Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/generic_object.rb
   30 /Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/common.rb
   31 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/enc/utf_16be.bundle
   32 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/enc/utf_16le.bundle
   33 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/enc/utf_32be.bundle
   34 /Users/herbyraynaud/.rbenv/versions/2.2.1/lib/ruby/2.2.0/x86_64-darwin14/enc/utf_32le.bundle
   35 /Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/ext/parser.bundle
   36 /Users/herbyraynaud/.gem/gems/json-1.8.2/lib/json/ext/generator.bundle

**Comment by eileencodes** [comment]
Hi @hraynaud, thanks for the issue report! I don't think this is caused by the gem. Let me know if you're still having the issue and I'll reopen.
