### ISSUE TITLE
Is this gem still being maintained?

### ISSUE THREAD

**Issue by mrsfixit** [sstephenson/global_phone#34]
@sstephenson, we've been eagerly awaiting updates on this outstanding gem, but its been 2 years now since the last release.
Totally understand if you're busy, but perhaps someone else (eg. someone at google) could pick up the mantle for your ruby port of the google library?
(https://github.com/googlei18n/libphonenumber/issues/704)

**Comment by nofxx** [comment]
Looks like a continuation:

https://github.com/daddyz/phonelib

**Comment by jeremy** [comment]
@eileencodes is sprucing this up. Phonelib looks like a good alternative, too!
