### ISSUE TITLE
global_phone_dbgen not generating the json file. 

### ISSUE THREAD

**Issue by johnpaulh** [sstephenson/global_phone#40]
This commit is not showing up in either release 1.0.0 or 1.01.  Because of which Http 404 error is thrown from global_phone_dbgen >>  command.

https://github.com/sstephenson/global_phone/commit/159a43733247d9f0165d44c27eaf80d791cdc220

Can you tag a new release with the above commit.
Regards,
John

**Comment by Luminus** [comment]
This issue still persists. 

Please help sort this out.

**Comment by eileencodes** [comment]
The new gem hasn't been released yet, but the issue is fixed in master on the commit mentioned. https://github.com/sstephenson/global_phone/pull/36

**Comment by Luminus** [comment]
Awesome stuff @eileencodes. Thanks.
